name: fedllm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anthropic==0.16.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bitsandbytes==0.40.2
      - blessed==1.20.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.13.0
      - dill==0.3.6
      - distro==1.9.0
      - docstring-parser==0.15
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - filelock==3.12.3
      - fire==0.5.0
      - fonttools==4.43.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gpustat==1.1.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - idna==3.4
      - install==1.3.5
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.5
      - lit==16.0.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.108
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openai==0.28.0
      - packaging==23.1
      - pandas==2.1.0
      - peft==0.4.0
      - pillow==10.1.0
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - rich==13.6.0
      - safetensors==0.4.2
      - scipy==1.11.2
      - sentencepiece==0.1.99
      - shtab==1.6.4
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.12
      - tenacity==8.2.3
      - termcolor==2.3.0
      - tiktoken==0.5.2
      - tokenizers==0.13.3
      - torch==2.0.1
      - tqdm==4.66.1
      - transformers==4.31.0
      - transformers-stream-generator==0.0.4
      - triton==2.0.0
      - trl==0.7.2
      - typing-extensions==4.7.1
      - tyro==0.5.10
      - tzdata==2023.3
      - urllib3==2.0.4
      - wcwidth==0.2.6
      - xxhash==3.3.0
      - yarl==1.9.2
prefix: /GPFS/rhome/ruige/miniconda3/envs/fedllm
